research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
  output_file: report.md

git_analysis_task:
  description: >
    Clone the project, generate and read the repo tree and read the README.md files if they exist.
  expected_output: > 
    A summary of structured hierarchical summary of the codebase 
    with clear distinction between the files that help accomplish the main goal of the repository and the auxiliary 
    files that provide secondary functionality and extra utilities.


party_shopping_task:
  description: >
    Generate a shopping list for a party with old doctor colleagues.
    The list should include all necessary supplies in a bullet point format, 
    categorized into food, beverages, and miscellaneous.
  expected_output: >
    A structured bullet point list of items categorized into food, beverages, and miscellaneous.
  agent: party_planner
shopping_prices_task:
  description: >
    Read the generated shopping list and assign prices for each item.
    Ensure the prices reflect a reasonable cost for 2024.
    Output the updated shopping list with each item followed by its price.
  expected_output: >
    A structured shopping list where each item has a price, formatted as:
      - Item: [Name] - Price: $[value]
      - Example: Bread - Price: $2.50
  agent: pricing_analyzer
