planner_task:
    description: |
      We're currently analyzing the following issue within our repository. 
      Here's the issue text:
        ISSUE: {issue}
        REPO: {repo}
        The error filepath is this: {gold_file_path}

      Understand the GitHub Issue and create a list of files that could be useful for the editor to examine and 
      solve the issue according to issue, issue_hing, error filepath.

      Don't try to clone the repository.
      The repo is already cloned and your current working directory is inside the 
      repo.

      Now, you're going solve the issue and guide a Code Editor to make changes to the code until you're 
      satisfied with all of the changes he's made. Then you can submit these changes to the code base by 
      simply running the submit command.
    expected_output: |
      Your response should contain the that after thorough analysis of the issue the editor needs to further examine,
      also for every file a small description on what is the reason this file could be problematic. 
      Furthermore give instructions on the next steps of hte editor agent my telling him how to examine the files.
    agent: planner

editor_task:
    description: |
      We're currently solving the following issue within our repository. 
      Here's the issue text:
        ISSUE: {issue}
        REPO: {repo}
      
      Your task is to examine the files returned by the planner and examine them to find out the improvements that 
      have to be done so that the issue is resolved and a Pull Request can be created for this repository.
    expected_output:
      First a list of changes the model did to the files, then the patch generated using the patch generation tool.
    agent: editor