european_translations_task:
    description: |
      Your task is to say {source_word} in 5 different languages. The languages should include:
        1. Greek
        2. Spanish
        3. French
        4. German
        5. Italian
      
      Ensure the translations are accurate and properly formatted in your output.
    expected_output: |
      Your response should include {source_word} in the 5 languages listed above.
    agent: translator